### ISSUE TITLE
hi作者

### ISSUE THREAD

**Issue by lkccu** [heyblackC/DFMIR#1]
请问一下我尝试用Learn2Reg2021TASK1的数据集去训练您的网络，但是我注意到在dataset_config中不支持.nii.gz的后缀，请问我是需要把nii.gz的图片转化成.jpg图片的形式再进行训练吗，如果是的话那请问需要沿哪个轴进行切片，或者是切下它最清晰的那一片呢？

**Comment by heyblackC** [comment]
hello同学，我们网络采用的是二维切片输入，因此确实需要先把nii.gz的图片转化成.jpg图片，这点在我们论文的Datasets部分有所描述。关于切片，我们是沿着z轴切，且限制在中央区域（因为volume的两端会出现全黑切片或者不包含分割mask）。

**Comment by lkccu** [comment]
谢谢同学！我明白了

**Comment by yehaowei** [comment]
Hello, can the processed data set be open source? I saw some mini data sets under get_data, downloaded and can be trained, but the test has no real data, thank you

**Comment by bhosalems** [comment]
> 谢谢同学！我明白了

Hi, i was wondering if you were able to re-train it on the learn2reg dataset.
